struct Town
       width            dd      ?
       height           dd      ?
       total            dd      ?
       ;scale            dd      ?
       pTowerModels     dd      ?
ends

towerModel    Model         <0,0,0,0,0,0>,\
                            <\
                                   <0.0, 0.0, 0.0>,\
                                   <0.0, 0.0, 0.0>,\
                                   <0.3, 0.3, 0.3>\
                            >


testTown      Town 