GL_VERTEX_SHADER=       0x8B31
GL_ARRAY_BUFFER =       0x8892
GL_ELEMENT_ARRAY_BUFFER = 0x8893
GL_STATIC_DRAW  =       0x88E4
GL_TEXTURE0     =       0x84C0
GL_MIRRORED_REPEAT      = 0x8370
GL_CLAMP_TO_BORDER      = 0x812D



textureNeonPath db              'D_textures\txtrTriangle.bmp',0
textureNeonID   GLuint          0

textureGroundPath db            'D_textures\hiResGroundPurple.bmp',0
textureGroundID   GLuint        0

textureRoadPath  db             'D_textures\txtrRoadway.bmp',0
textureRoadID     GLuint        0