struct Vector3
        x       GLfloat      ?
        y       GLfloat      ?
        z       GLfloat      ?
ends

struct Vector4
        x       GLfloat      ?
        y       GLfloat      ?
        z       GLfloat      ?
        w       GLfloat      ?
ends

struct ColorRGBA
        r       GLfloat      ?
        g       GLfloat      ?
        b       GLfloat      ?
        a       GLfloat      ?
ends

VecUpward       Vector3         0.0, 1.0, 0.0
nullVector          Vector3     0.0, 0.0, 0.0