PLANE_TRIANGLES_COUNT   =       2
PLANE_VERTICES_COUNT    =       PLANE_TRIANGLES_COUNT * 3

planeVertices:
                GLfloat -8.0, -1.0, -8.0
                GLfloat -8.0, -1.0,  8.0
                GLfloat  8.0, -1.0,  8.0
                GLfloat -8.0, -1.0, -8.0
                GLfloat  8.0, -1.0,  8.0
                GLfloat  8.0, -1.0, -8.0

planeColors     GLfloat 0.0, 0.0, 1.0,\
                        0.0, 0.0, 1.0,\
                        0.0, 0.0, 1.0,\
                        0.0, 0.0, 1.0,\
                        0.0, 0.0, 1.0,\
                        0.0, 0.0, 1.0