PLANE_TRIANGLES_COUNT   =       2

planeVertices:
        GLfloat         -30.0, 0.0, -30.0
        GLfloat         -30.0, 0.0, 30.0
        GLfloat         30.0, 0.0, 30.0
        GLfloat         30.0, 0.0, -30.0
planeTexCoords:
        GLfloat         0.0, 60.0
        GLfloat         0.0, 0.0
        GLfloat         60.0, 0.0
        GLfloat         60.0, 60.0

planeIndices:
        db          0, 1, 2,\
                    2, 3, 0