PLANE_TRIANGLES_COUNT   =       2

planeVertices:
        GLfloat         -10.0, 0.0, -10.0
        GLfloat         -10.0, 0.0, 10.0
        GLfloat         10.0, 0.0, 10.0
        GLfloat         10.0, 0.0, -10.0
planeTexCoords:
        GLfloat         0.0, 10.0
        GLfloat         0.0, 0.0
        GLfloat         10.0, 0.0
        GLfloat         10.0, 10.0

planeIndices:
        db          0, 1, 2,\
                    2, 3, 0