track1msgs:
       UnprocessedMessage        <FSh3, 1.33, 0.0>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.33, 0.0>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.33, 0.0>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.810468,1.364635>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.810468,1.364635>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.810468,1.364635>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.214739,2.403697>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.214739,2.403697>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.214739,2.403697>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.265156,2.666927>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.265156,2.666927>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.265156,2.666927>, INSTR_SYNTH


       UnprocessedMessage        <FSh4,1.33,5.326927>, INSTR_SYNTH
       UnprocessedMessage        <D4,1.33,5.326927>, INSTR_SYNTH
       UnprocessedMessage        <B3,1.33,5.326927>, INSTR_SYNTH

       UnprocessedMessage        <G4,0.810468,6.691562>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.810468,6.691562>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.810468,6.691562>, INSTR_SYNTH

       UnprocessedMessage        <G4,0.214739,7.730624>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.214739,7.730624>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.214739,7.730624>, INSTR_SYNTH

       UnprocessedMessage        <A4,2.265156,7.993854>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.265156,7.993854>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.265156,7.993854>, INSTR_SYNTH


       UnprocessedMessage        <FSh3, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <FSh4, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.33, 10.646927>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.810468,12.011562>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.214739,13.050625>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <A4,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.265156,13.313854>, INSTR_SYNTH





       UnprocessedMessage        <FSh3, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <FSh4, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.339427, 15.980781>, INSTR_SYNTH
       UnprocessedMessage        <FSh6, 0.3325, 16.320208>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.325572, 16.659635>, INSTR_SYNTH
       UnprocessedMessage        <B5, 0.3325, 16.94>, INSTR_SYNTH


       UnprocessedMessage        <G3,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.3325, 17.310781>, INSTR_SYNTH
       UnprocessedMessage        <FSh6, 0.325572, 17.650208>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.318645, 17.989635>, INSTR_SYNTH
       UnprocessedMessage        <C6, 0.3325, 18.308281>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.214739,18.377552>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <A4,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <F6, 0.4294790, 18.668489>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.200885, 19.084114>, INSTR_SYNTH
       UnprocessedMessage        <G6, 0.200885, 19.215729>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.415625, 19.388906>, INSTR_SYNTH


TRACK1_MESSAGESCOUNT = ($-track1msgs)/sizeof.UnprocessedMessage


; array of sequencers
track1seqs:

TRACK1_SEQUENCERSCOUNT = ($-track1seqs)/sizeof.Sequencer


; sequencer messages
track1seqs.messages:

TRACK1_SEQMSGSCOUNT = ($-track1seqs)/sizeof.Sequencer

track1      Track       21.28, 0