SG1_SpectatorStart.Msgs:

       ; UnprocessedMessage        <G1, KICK_TIME, 0.0>, INSTR_KICK
       ; UnprocessedMessage        <A4, 1.0, 0.0>, INSTR_SNARETAIL
       ; UnprocessedMessage        <FSh1, 1.0, 0.0>, INSTR_SNAREBODY
       ; UnprocessedMessage        <E3, 0.5, 0.0>, INSTR_PADS


       UnprocessedMessage        <FSh3, 1.33, 0.0>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.33, 0.0>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.33, 0.0>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.810468,1.364635>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.810468,1.364635>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.810468,1.364635>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.214739,2.403697>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.214739,2.403697>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.214739,2.403697>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.265156,2.666927>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.265156,2.666927>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.265156,2.666927>, INSTR_SYNTH


       UnprocessedMessage        <FSh4,1.33,5.326927>, INSTR_SYNTH
       UnprocessedMessage        <D4,1.33,5.326927>, INSTR_SYNTH
       UnprocessedMessage        <B3,1.33,5.326927>, INSTR_SYNTH

       UnprocessedMessage        <G4,0.810468,6.691562>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.810468,6.691562>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.810468,6.691562>, INSTR_SYNTH

       UnprocessedMessage        <G4,0.214739,7.730624>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.214739,7.730624>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.214739,7.730624>, INSTR_SYNTH

       UnprocessedMessage        <A4,2.265156,7.993854>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.265156,7.993854>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.265156,7.993854>, INSTR_SYNTH


       UnprocessedMessage        <FSh3, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <FSh4, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.33, 10.646927>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.33, 10.646927>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.810468,12.011562>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.810468,12.011562>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.214739,13.050625>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.214739,13.050625>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <A4,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.265156,13.313854>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.265156,13.313854>, INSTR_SYNTH





       UnprocessedMessage        <FSh3, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <FSh4, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.33, 15.96>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.339427, 15.980781>, INSTR_SYNTH
       UnprocessedMessage        <FSh6, 0.3325, 16.320208>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.325572, 16.659635>, INSTR_SYNTH
       UnprocessedMessage        <B5, 0.3325, 16.94>, INSTR_SYNTH


       UnprocessedMessage        <G3,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.810468,17.338489>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.3325, 17.310781>, INSTR_SYNTH
       UnprocessedMessage        <FSh6, 0.325572, 17.650208>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.318645, 17.989635>, INSTR_SYNTH
       UnprocessedMessage        <C6, 0.3325, 18.308281>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.214739,18.377552>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.214739,18.377552>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <A4,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.265156,18.62>, INSTR_SYNTH
       UnprocessedMessage        <F6, 0.4294790, 18.668489>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.200885, 19.084114>, INSTR_SYNTH
       UnprocessedMessage        <G6, 0.200885, 19.215729>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.415625, 19.388906>, INSTR_SYNTH

       UnprocessedMessage        <E3, 2.66, 21.28>, INSTR_BASS
       UnprocessedMessage        <G3, 2.66, 23.94>, INSTR_BASS
       UnprocessedMessage        <B3, 2.66, 26.6>, INSTR_BASS
       UnprocessedMessage        <A3, 2.66, 29.26>, INSTR_BASS

       UnprocessedMessage        <E2, 0.33, 30.75625>, INSTR_TOM
       UnprocessedMessage        <CSh2, 0.33, 30.9225>, INSTR_TOM
       UnprocessedMessage        <B1, 0.33, 31.08875>, INSTR_TOM
       UnprocessedMessage        <D2, 0.33, 31.255>, INSTR_TOM
       UnprocessedMessage        <A1, 0.33, 31.75375>, INSTR_TOM

       UnprocessedMessage        <FSh1, 0.16625, 30.75625>, INSTR_SNAREBODY
       UnprocessedMessage        <A1, 0.16625, 30.75625>, INSTR_SNARETAIL
       UnprocessedMessage        <FSh1, 0.16625, 31.255>, INSTR_SNAREBODY
       UnprocessedMessage        <A1, 0.16625, 31.255>, INSTR_SNARETAIL
       UnprocessedMessage        <FSh1, 0.16625, 31.75375>, INSTR_SNAREBODY
       UnprocessedMessage        <A1, 0.16625, 31.75375>, INSTR_SNARETAIL

SG1_SpectatorStart.MsgsCount = ($-SG1_SpectatorStart.Msgs)/sizeof.UnprocessedMessage


; array of sequencers
SG1_SpectatorStart.Seqs:
       ; Sequencer            SG1_SpectatorStart.SeqMsgs, SG1_SpectatorStart.SeqMsgsCount, 90.0, 0.0, 4, 4
SG1_SpectatorStart.SeqCount = ($-SG1_SpectatorStart.Seqs)/sizeof.Sequencer


; sequencer messages
SG1_SpectatorStart.SeqMsgs:
       ; SeqMessage           mytestmessage, 0111111111111111b
SG1_SpectatorStart.SeqMsgsCount = ($-SG1_SpectatorStart.SeqMsgs)/sizeof.SeqMessage

; mytestmessage        UnprocessedMessage <A1, 0.131614, ?>, INSTR_HIHAT