templatePackedCross         PackedVerticesMesh      planeVertices, planeIndices, crossTexCoords, PLANE_TRIANGLES_COUNT

Crossroad13   Model         <0,0,0,0,0,0>,\
                            <\
                                   <0.0, 0.0, 0.0>,\
                                   <0.0, 0.0, 0.0>,\
                                   <4.0, 4.0, 4.0>\   
                            >

Crossroad23   Model         <0,0,0,0,0,0>,\
                            <\
                                   <0.0, 0.0, 128.0>,\
                                   <0.0, 0.0, 0.0>,\
                                   <4.0, 4.0, 4.0>\   
                            >

Crossroad33   Model         <0,0,0,0,0,0>,\
                            <\
                                   <0.0, 0.0, 256.0>,\
                                   <0.0, 0.0, 0.0>,\
                                   <4.0, 4.0, 4.0>\   
                            >