ST_RunnerSecond.Msgs:

       UnprocessedMessage        <D3, 0.3333333333, 0.3333333333>, INSTR_KEY
       UnprocessedMessage        <E3, 0.3333333333, 0.666666666>, INSTR_KEY
       UnprocessedMessage        <G3, 0.3333333333, 1.0>, INSTR_KEY
       UnprocessedMessage        <B3, 0.3333333333, 1.333333333>, INSTR_KEY
       UnprocessedMessage        <E3, 0.3333333333, 2.0>, INSTR_KEY
       UnprocessedMessage        <B3, 0.3333333333, 2.333333333>, INSTR_KEY

       ; UnprocessedMessage        <B4, 0.3333333333, 2.666666666>, INSTR_KEY
       UnprocessedMessage        <D3, 0.3333333333, 3.0>, INSTR_KEY
       UnprocessedMessage        <E3, 0.3333333333, 3.333333333>, INSTR_KEY
       UnprocessedMessage        <G3, 0.3333333333, 3.666666666>, INSTR_KEY
       UnprocessedMessage        <B3, 0.3333333333, 4.0>, INSTR_KEY
       UnprocessedMessage        <G3, 0.3333333333, 4.333333333>, INSTR_KEY
       UnprocessedMessage        <B3, 0.3333333333, 4.666666666>, INSTR_KEY
       ; UnprocessedMessage        <B4, 0.3333333333, 5.0>, INSTR_KEY

       UnprocessedMessage        <E3, 0.3333333333, 5.666666666>, INSTR_KEY
       UnprocessedMessage        <G3, 0.3333333333, 6.0>, INSTR_KEY
       UnprocessedMessage        <B3, 0.3333333333, 6.333333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.3333333333, 6.666666666>, INSTR_KEY
       UnprocessedMessage        <D4, 0.3333333333, 7.0>, INSTR_KEY
       UnprocessedMessage        <E4, 0.3333333333, 7.333333333>, INSTR_KEY
       UnprocessedMessage        <F4, 0.3333333333, 7.666666666>, INSTR_KEY

       UnprocessedMessage        <E4, 0.3333333333, 8.0>, INSTR_KEY
       UnprocessedMessage        <D4, 0.3333333333, 8.333333333>, INSTR_KEY
       UnprocessedMessage        <F4, 0.3333333333, 8.666666666>, INSTR_KEY
       UnprocessedMessage        <A4, 0.3333333333, 9.0>, INSTR_KEY
       UnprocessedMessage        <C5, 0.3333333333, 9.333333333>, INSTR_KEY
       UnprocessedMessage        <D5, 0.3333333333, 9.666666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.5, 10.0>, INSTR_KEY



       UnprocessedMessage        <E5, 0.166666666, 10.66666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 10.83333333>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 11.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 11.16666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 12.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 12.16666666>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 12.33333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 12.5>, INSTR_KEY


       UnprocessedMessage        <E5, 0.166666666, 13.33333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 13.5>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 13.66666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 13.83333333>, INSTR_KEY
       UnprocessedMessage        <B4, 0.166666666, 14.16666666>, INSTR_KEY
       UnprocessedMessage        <B4, 0.166666666, 14.33333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 14.66666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 14.83333333>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 15.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 15.16666666>, INSTR_KEY

       UnprocessedMessage        <E5, 0.166666666, 16.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 16.166666666>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 16.333333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 16.5>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 17.333333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 17.5>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 17.666666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 17.833333333>, INSTR_KEY
       UnprocessedMessage        <F5, 0.166666666, 18.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 18.166666666>, INSTR_KEY
       UnprocessedMessage        <G5, 0.166666666, 18.333333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 18.5>, INSTR_KEY
       
       UnprocessedMessage        <E5, 0.166666666, 18.666666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 18.833333333>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 19.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 19.166666666>, INSTR_KEY
       UnprocessedMessage        <F5, 0.166666666, 19.333333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 19.5>, INSTR_KEY
       UnprocessedMessage        <G5, 0.166666666, 19.666666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 19.833333333>, INSTR_KEY
       ; UnprocessedMessage        <E5, 0.166666666, 20.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 20.166666666>, INSTR_KEY
       UnprocessedMessage        <D5, 0.166666666, 20.333333333>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 20.5>, INSTR_KEY
       UnprocessedMessage        <F5, 0.166666666, 20.666666666>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 20.833333333>, INSTR_KEY
       UnprocessedMessage        <G5, 0.166666666, 21.0>, INSTR_KEY
       UnprocessedMessage        <E5, 0.166666666, 21.166666666>, INSTR_KEY




       UnprocessedMessage        <G4, 0.16666666666, 22.16666666666>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 22.33333333333>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 22.5>, INSTR_KEY
       UnprocessedMessage        <D5, 0.16666666666, 22.66666666666>, INSTR_KEY
       UnprocessedMessage        <C5, 0.16666666666, 23.0>, INSTR_KEY
       UnprocessedMessage        <B4, 0.16666666666, 23.33333333333>, INSTR_KEY
       UnprocessedMessage        <A4, 0.16666666666, 23.66666666666>, INSTR_KEY

       UnprocessedMessage        <G4, 0.16666666666, 24.833333333>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 25.0>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 25.166666666>, INSTR_KEY
       UnprocessedMessage        <D5, 0.16666666666, 25.333333333>, INSTR_KEY
       UnprocessedMessage        <C5, 0.16666666666, 25.666666666>, INSTR_KEY
       UnprocessedMessage        <B4, 0.16666666666, 26.0>, INSTR_KEY
       UnprocessedMessage        <A4, 0.16666666666, 26.333333333>, INSTR_KEY

       UnprocessedMessage        <B4, 0.16666666666, 26.666666666>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 27.166666666>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 27.666666666>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 28.833333333>, INSTR_KEY
       UnprocessedMessage        <A4, 0.16666666666, 29.0>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 29.166666666>, INSTR_KEY


       UnprocessedMessage        <B4, 0.16666666666, 29.333333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 29.833333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 30.333333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 31.0>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 31.333333333>, INSTR_KEY
       UnprocessedMessage        <D4, 0.16666666666, 31.5>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 31.666666666>, INSTR_KEY
       UnprocessedMessage        <A4, 0.16666666666, 31.833333333>, INSTR_KEY



       UnprocessedMessage        <G4, 0.16666666666, 32.83333333>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 33.0>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 33.16666666>, INSTR_KEY
       UnprocessedMessage        <D5, 0.16666666666, 33.33333333>, INSTR_KEY
       UnprocessedMessage        <C5, 0.16666666666, 33.66666666>, INSTR_KEY
       UnprocessedMessage        <B4, 0.16666666666, 34.0>, INSTR_KEY
       UnprocessedMessage        <A4, 0.16666666666, 34.33333333>, INSTR_KEY

       UnprocessedMessage        <G4, 0.16666666666, 35.5>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 35.66666666>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 35.83333333>, INSTR_KEY
       UnprocessedMessage        <D5, 0.16666666666, 36.0>, INSTR_KEY
       UnprocessedMessage        <C5, 0.16666666666, 36.33333333>, INSTR_KEY
       UnprocessedMessage        <B4, 0.16666666666, 36.66666666>, INSTR_KEY
       UnprocessedMessage        <A4, 0.16666666666, 37.0>, INSTR_KEY

       UnprocessedMessage        <B4, 0.16666666666, 37.3333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 37.8333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 38.3333333>, INSTR_KEY
       UnprocessedMessage        <E4, 0.16666666666, 39.5>, INSTR_KEY
       UnprocessedMessage        <G4, 0.16666666666, 39.8333333>, INSTR_KEY

       UnprocessedMessage        <B4, 0.33333333333, 40.0>, INSTR_KEY
       UnprocessedMessage        <A4, 0.33333333333, 40.5>, INSTR_KEY
       UnprocessedMessage        <A4, 0.33333333333, 41.0>, INSTR_KEY
       UnprocessedMessage        <D4, 0.33333333333, 41.5>, INSTR_KEY
       UnprocessedMessage        <E4, 0.33333333333, 42.0>, INSTR_KEY
       UnprocessedMessage        <A4, 0.33333333333, 42.33333333>, INSTR_KEY





       UnprocessedMessage        <E3, 2.666666666, 0.0>, INSTR_BASS
       UnprocessedMessage        <E2, 2.666666666, 0.0>, INSTR_PADS
       UnprocessedMessage        <E3, 2.666666666, 0.0>, INSTR_PADS
       UnprocessedMessage        <E5, 2.666666666, 0.0>, INSTR_PADS
       UnprocessedMessage        <G3, 2.666666666, 2.666666666>, INSTR_BASS
       UnprocessedMessage        <G2, 2.666666666, 2.666666666>, INSTR_PADS
       UnprocessedMessage        <G3, 2.666666666, 2.666666666>, INSTR_PADS
       UnprocessedMessage        <G5, 2.666666666, 2.666666666>, INSTR_PADS
       UnprocessedMessage        <B3, 2.666666666, 5.33333333>, INSTR_BASS
       UnprocessedMessage        <B2, 2.666666666, 5.33333333>, INSTR_PADS
       UnprocessedMessage        <B3, 2.666666666, 5.33333333>, INSTR_PADS
       UnprocessedMessage        <B5, 2.666666666, 5.33333333>, INSTR_PADS
       UnprocessedMessage        <A3, 2.666666666, 8.0>, INSTR_BASS
       UnprocessedMessage        <A2, 2.666666666, 8.0>, INSTR_PADS
       UnprocessedMessage        <A3, 2.666666666, 8.0>, INSTR_PADS
       UnprocessedMessage        <A5, 2.666666666, 8.0>, INSTR_PADS

       UnprocessedMessage        <E3, 2.666666666, 10.666666666>, INSTR_BASS
       UnprocessedMessage        <E2, 2.666666666, 10.666666666>, INSTR_PADS
       UnprocessedMessage        <E3, 2.666666666, 10.666666666>, INSTR_PADS
       UnprocessedMessage        <E5, 2.666666666, 10.666666666>, INSTR_PADS 
       UnprocessedMessage        <G3, 2.666666666, 13.333333333>, INSTR_BASS
       UnprocessedMessage        <G2, 2.666666666, 13.333333333>, INSTR_PADS 
       UnprocessedMessage        <G3, 2.666666666, 13.333333333>, INSTR_PADS 
       UnprocessedMessage        <G5, 2.666666666, 13.333333333>, INSTR_PADS 
       UnprocessedMessage        <B3, 2.666666666, 16.0>, INSTR_BASS
       UnprocessedMessage        <B2, 2.666666666, 16.0>, INSTR_PADS
       UnprocessedMessage        <B3, 2.666666666, 16.0>, INSTR_PADS
       UnprocessedMessage        <B5, 2.666666666, 16.0>, INSTR_PADS 
       UnprocessedMessage        <A3, 2.666666666, 18.666666666>, INSTR_BASS
       UnprocessedMessage        <A2, 2.666666666, 18.666666666>, INSTR_PADS
       UnprocessedMessage        <A3, 2.666666666, 18.666666666>, INSTR_PADS
       UnprocessedMessage        <A5, 2.666666666, 18.666666666>, INSTR_PADS



       UnprocessedMessage        <C3, 2.666666666, 21.333333333>, INSTR_BASS
       UnprocessedMessage        <C2, 2.666666666, 21.333333333>, INSTR_PADS 
       UnprocessedMessage        <C3, 2.666666666, 21.333333333>, INSTR_PADS 
       UnprocessedMessage        <C5, 2.666666666, 21.333333333>, INSTR_PADS 
       UnprocessedMessage        <D3, 2.666666666, 24.0>, INSTR_BASS
       UnprocessedMessage        <D2, 2.666666666, 24.0>, INSTR_PADS 
       UnprocessedMessage        <D3, 2.666666666, 24.0>, INSTR_PADS 
       UnprocessedMessage        <D5, 2.666666666, 24.0>, INSTR_PADS 
       UnprocessedMessage        <E3, 4.0, 26.6666666>, INSTR_BASS
       UnprocessedMessage        <E2, 4.0, 26.6666666>, INSTR_PADS
       UnprocessedMessage        <E3, 4.0, 26.6666666>, INSTR_PADS
       UnprocessedMessage        <E5, 4.0, 26.6666666>, INSTR_PADS
       UnprocessedMessage        <D3, 1.333333333, 30.6666666>, INSTR_BASS
       UnprocessedMessage        <D2, 1.333333333, 30.6666666>, INSTR_PADS
       UnprocessedMessage        <D3, 1.333333333, 30.6666666>, INSTR_PADS
       UnprocessedMessage        <D5, 1.333333333, 30.6666666>, INSTR_PADS

       UnprocessedMessage        <C3, 2.666666666, 32.0>, INSTR_BASS
       UnprocessedMessage        <C2, 2.666666666, 32.0>, INSTR_PADS 
       UnprocessedMessage        <C3, 2.666666666, 32.0>, INSTR_PADS
       UnprocessedMessage        <C5, 2.666666666, 32.0>, INSTR_PADS
       UnprocessedMessage        <D3, 2.666666666, 34.6666666>, INSTR_BASS
       UnprocessedMessage        <D2, 2.666666666, 34.6666666>, INSTR_PADS 
       UnprocessedMessage        <D3, 2.666666666, 34.6666666>, INSTR_PADS
       UnprocessedMessage        <D5, 2.666666666, 34.6666666>, INSTR_PADS
       UnprocessedMessage        <E3, 4.666666666, 37.33333333>, INSTR_BASS
       UnprocessedMessage        <E2, 4.666666666, 37.33333333>, INSTR_PADS
       UnprocessedMessage        <E3, 4.666666666, 37.33333333>, INSTR_PADS 
       UnprocessedMessage        <E5, 4.666666666, 37.33333333>, INSTR_PADS
       UnprocessedMessage        <D3, 0.666666666, 42.0>, INSTR_BASS
       UnprocessedMessage        <D2, 0.666666666, 42.0>, INSTR_PADS
       UnprocessedMessage        <D3, 0.666666666, 42.0>, INSTR_PADS
       UnprocessedMessage        <D5, 0.666666666, 42.0>, INSTR_PADS

ST_RunnerSecond.MsgsCount = ($-ST_RunnerSecond.Msgs)/sizeof.UnprocessedMessage



ST_RunnerSecond.Seqs:
       Sequencer                 ST_RunnerSecond.Drums, ST_RunnerSecond.DrumsCount, 90.0, 0.0, 4, 4 
ST_RunnerSecond.SeqsCount = ($-ST_RunnerSecond.Seqs)/sizeof.Sequencer



ST_RunnerSecond.Drums:
       SeqMessage                ST_RunnerSecond.HiHat,     1111111111111111b
       SeqMessage                ST_RunnerSecond.Kick,      0000000100000001b
       SeqMessage                ST_RunnerSecond.SnareBody, 0001000000010000b
       SeqMessage                ST_RunnerSecond.SnareTail, 0001000000010000b             
ST_RunnerSecond.DrumsCount = ($-ST_RunnerSecond.Drums)/sizeof.SeqMessage


ST_RunnerSecond.HiHat       UnprocessedMessage      <A1, 0.131614, ?>, INSTR_HIHAT
ST_RunnerSecond.Kick        UnprocessedMessage      <G1, KICK_TIME, ?>, INSTR_KICK 
ST_RunnerSecond.SnareBody   UnprocessedMessage      <FSh1, 1.0, ?>, INSTR_SNAREBODY
ST_RunnerSecond.SnareTail   UnprocessedMessage      <A4, 1.0, ?>, INSTR_SNARETAIL