ST_Start.Msgs:

       ; UnprocessedMessage        <G1, KICK_TIME, 0.0>, INSTR_KICK
       ; UnprocessedMessage        <A4, 1.0, 0.0>, INSTR_SNARETAIL
       ; UnprocessedMessage        <FSh1, 1.0, 0.0>, INSTR_SNAREBODY
       ; UnprocessedMessage        <E3, 0.5, 0.0>, INSTR_PADS

       UnprocessedMessage        <FSh3, 1.3333333, 0.0>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.3333333, 0.0>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.3333333, 0.0>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.8125,1.3680555>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.8125,1.3680555>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.8125,1.3680555>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.2152777,2.403697>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.2152777,2.403697>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.2152777,2.403697>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.2708333,2.6736111>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.2708333,2.6736111>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.2708333,2.6736111>, INSTR_SYNTH


       UnprocessedMessage        <FSh4, 1.3333333,5.34027777>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.3333333,5.34027777>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.3333333,5.34027777>, INSTR_SYNTH

       UnprocessedMessage        <G4,0.8125,6.70833333>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.8125,6.70833333>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.8125,6.70833333>, INSTR_SYNTH

       UnprocessedMessage        <G4,0.2152777,7.7499999>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.2152777,7.7499999>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.2152777,7.7499999>, INSTR_SYNTH

       UnprocessedMessage        <A4,2.2708333,8.0138888>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.2708333,8.0138888>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.2708333,8.0138888>, INSTR_SYNTH


       UnprocessedMessage        <FSh3, 1.3333333, 10.673611>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.3333333, 10.673611>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.3333333, 10.673611>, INSTR_SYNTH
       UnprocessedMessage        <FSh4, 1.3333333, 10.673611>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.3333333, 10.673611>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.3333333, 10.673611>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.8125,12.0416666>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.8125,12.0416666>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.8125,12.0416666>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.8125,12.0416666>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.8125,12.0416666>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.8125,12.0416666>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.2152777,13.083333>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.2152777,13.083333>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.2152777,13.083333>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.2152777,13.083333>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.2152777,13.083333>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.2152777,13.083333>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.2708333,13.3472222>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.2708333,13.3472222>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.2708333,13.3472222>, INSTR_SYNTH
       UnprocessedMessage        <A4,2.2708333,13.3472222>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.2708333,13.3472222>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.2708333,13.3472222>, INSTR_SYNTH





       UnprocessedMessage        <FSh3, 1.3333333, 16.013888>, INSTR_SYNTH
       UnprocessedMessage        <D3, 1.3333333, 16.013888>, INSTR_SYNTH
       UnprocessedMessage        <B2, 1.3333333, 16.013888>, INSTR_SYNTH
       UnprocessedMessage        <FSh4, 1.3333333, 16.013888>, INSTR_SYNTH
       UnprocessedMessage        <D4, 1.3333333, 16.013888>, INSTR_SYNTH
       UnprocessedMessage        <B3, 1.3333333, 16.013888>, INSTR_SYNTH


       UnprocessedMessage        <G3,0.8125,17.381944>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.8125,17.381944>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.8125,17.381944>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.8125,17.381944>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.8125,17.381944>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.8125,17.381944>, INSTR_SYNTH

       UnprocessedMessage        <G3,0.2152777,18.423611>, INSTR_SYNTH
       UnprocessedMessage        <DSh3,0.2152777,18.423611>, INSTR_SYNTH
       UnprocessedMessage        <C3,0.2152777,18.423611>, INSTR_SYNTH
       UnprocessedMessage        <G4,0.2152777,18.423611>, INSTR_SYNTH
       UnprocessedMessage        <DSh4,0.2152777,18.423611>, INSTR_SYNTH
       UnprocessedMessage        <C4,0.2152777,18.423611>, INSTR_SYNTH

       UnprocessedMessage        <A3,2.2708333,18.68749999>, INSTR_SYNTH
       UnprocessedMessage        <F3,2.2708333,18.68749999>, INSTR_SYNTH
       UnprocessedMessage        <D3,2.2708333,18.68749999>, INSTR_SYNTH
       UnprocessedMessage        <A4,2.2708333,18.68749999>, INSTR_SYNTH
       UnprocessedMessage        <F4,2.2708333,18.68749999>, INSTR_SYNTH
       UnprocessedMessage        <D4,2.2708333,18.68749999>, INSTR_SYNTH


       
       UnprocessedMessage        <A6, 0.3402777, 16.020833>, INSTR_SYNTH
       UnprocessedMessage        <FSh6, 0.3333333, 16.36111111>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.32638888, 16.701388>, INSTR_SYNTH
       UnprocessedMessage        <B5, 0.3333333, 17.0208333>, INSTR_SYNTH
       
       UnprocessedMessage        <A6, 0.3402777, 17.354166>, INSTR_SYNTH
       UnprocessedMessage        <FSh6, 0.3333333, 17.694444>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.32638888, 18.034722>, INSTR_SYNTH
       UnprocessedMessage        <C6, 0.3333333, 18.3541666>, INSTR_SYNTH
       
       UnprocessedMessage        <F6, 0.4305555, 18.7152777>, INSTR_SYNTH
       UnprocessedMessage        <A6, 0.201388, 19.1319444>, INSTR_SYNTH
       UnprocessedMessage        <G6, 0.2013888, 19.26388888>, INSTR_SYNTH
       UnprocessedMessage        <D6, 0.41666666, 19.4375>, INSTR_SYNTH



       UnprocessedMessage        <E3, 2.6666666,  21.33333333>, INSTR_BASS
       UnprocessedMessage        <G3, 2.6666666, 24.0>, INSTR_BASS
       UnprocessedMessage        <B3, 2.6666666, 26.6666666>, INSTR_BASS
       UnprocessedMessage        <A3, 2.6666666, 29.3333333>, INSTR_BASS

       UnprocessedMessage        <E2, 0.33333333, 30.833333333>, INSTR_TOM
       UnprocessedMessage        <CSh2, 0.33333333, 31.0>, INSTR_TOM
       UnprocessedMessage        <B1, 0.33333333, 31.16666666>, INSTR_TOM
       UnprocessedMessage        <D2, 0.33333333,  31.3333333>, INSTR_TOM
       UnprocessedMessage        <A1, 0.33333333, 31.8333333>, INSTR_TOM

       UnprocessedMessage        <FSh1, 0.16625, 30.8333333>, INSTR_SNAREBODY
       UnprocessedMessage        <A1, 0.16625, 30.8333333>, INSTR_SNARETAIL
       UnprocessedMessage        <FSh1, 0.16625,  31.33333333>, INSTR_SNAREBODY
       UnprocessedMessage        <A1, 0.16625,  31.33333333>, INSTR_SNARETAIL
       UnprocessedMessage        <FSh1, 0.16625, 31.83333333>, INSTR_SNAREBODY
       UnprocessedMessage        <A1, 0.16625, 31.83333333>, INSTR_SNARETAIL

ST_Start.MsgsCount = ($-ST_Start.Msgs)/sizeof.UnprocessedMessage


; array of sequencers
ST_Start.Seqs:
       ; Sequencer            SG1_SpectatorStart.SeqMsgs, SG1_SpectatorStart.SeqMsgsCount, 90.0, 0.0, 4, 4
ST_Start.SeqsCount = ($-ST_Start.Seqs)/sizeof.Sequencer


; sequencer messages
ST_Start.SeqMsgs:
       ; SeqMessage           mytestmessage, 0111111111111111b
ST_Start.SeqMsgsCount = ($-ST_Start.SeqMsgs)/sizeof.SeqMessage

; mytestmessage        UnprocessedMessage <A1, 0.131614, ?>, INSTR_HIHAT